example: 80.238.9.179,1635769380,SIGNIN_FAILURE,Andy.Branning
fixedRate : 5000
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG